Radiation Transport Code: SolverRegMOC Class Reference
SolverRegMOC Class Reference
LocalMOC Solver.
#include <solverregmoc.h>
Public Member Functions
SolverRegMOC (TransportProblem &tp)
~SolverRegMOC ()
void solve ()
Implementation of the LocalMOC solver.
double * getResidual ()
double getScalarFlux (long space_i, int group_g)
Public Member Functions inherited from SolverBase
virtual ~SolverBase ()
double calculateL2SolutionNorm (double *solutionComp)
double calculateLInfSolutionNorm (double *solutionComp)
double calculateRInfSolutionNorm (double *solutionComp)
double calculateL2SolutionError ()
double calculateRInfSolutionError ()
const double * getSolutionValue (long space_i, int quad_n, int group_g)
const double * getSolutionValue (long i)
long getNumDOFs ()
TransportProblem & getTransportProblem ()
double getNeutronProduction (long space_i)
double getTotalNeutronProduction ()
void setRInfTol (double tol)
void setMaxIters (int maxIters)
void setSolution (double *solution)
double * copySolution (double *solutionCopy)
void normalizeSolution (double totalProductionRate)
void zeroSolution ()
void extrapolateSolution (double expExtrapFactor)
void extrapolateSolution (double expExtrapFactor, double *baseSolution)
void writeSolution (Output *outputFile)
void writeScalarFlux (Output *outputFile)
void printIterStatus (std::string name, int iter, double err, double tol)
Private Member Functions
long _dofIndex (long i, int n, int g, int edgeLoc=0)
long _dofIndexPS (long i, int n, int g, int subCell=0)
void _mapDOFs ()
Map degrees-of-freedom.
void _calculateSphericalQuadrature ()
Get spherical representation of ordinates.
int _getReflectedDirection (int i, double nx, double ny, double &OmegaDotn)
void _sweep (int n)
Mesh sweep.
void _getTriangleOrientation (UltraLightElement &element2, int &n, TriangleDescriptorReg &tri, int &blockID, double &theta, int &v0, int &v1, int &v2)
void _applyBoundaryConditions ()
double _getAngleFromVector (double dx, double dy)
Calculate the azimuthal angle of a vector with components dx and dy.
void _calculateSource (double *fissionFlux)
void _getExternalSource ()
void _addScatterSource ()
void _calculateMatrixAction (double *x, double *y)
double getSubCellScalarFlux (long space_i, int group_g, int subCell)
void triangleSolveA (TriangleDescriptorReg &tri, double &phi, double &theta, double &mu, long &elementID, int &n, int &g)
void triangleSolveB (TriangleDescriptorReg &tri, double &phi, double &theta, double &mu, long &elementID, int &n, int &g)
void triangleSolveEV (double &q, double &S, double &sigma, double &x, double &psi1, double &psi2, double &psi20, double &psi01, double &cell, double &psiv)
void triangleSolveVE2 (double &q, double &S, double &sigma, double &w1, double &w2, double &w3, double &psi0r, double &psi0l, double &psi1, double &psi2, double &psi12, double &cell)
Private Attributes
std::vector< double > _mu
std::vector< double > _theta
std::vector< int > _negDir
MoabMesh * mesh
double * _cellFlux
unsigned int _numPhaseSpaceDOF
Additional Inherited Members
Public Attributes inherited from SolverBase
SourceConfiguration sourceConfig
double sourceScaling
This scales the external source, but is used as a fission source in the power method.
double criticalEigenvalue
"Critical" eigenvalue for transient calculations based on ICs from an eigenvalue calculation
Protected Member Functions inherited from SolverBase
SolverBase (TransportProblem &tp)
Constructor.
void _calculateResidual ()
void _saveOldSolution ()
Protected Attributes inherited from SolverBase
TransportProblem & _prob
Reference to the base transport problem.
long _numDOF
Number of DOF.
long _numSpaceDOF
Number of spatial DOF.
std::vector< DOFObj > DOFlist
List of DOF (currently unused)
std::map< DOFObj, double * > DOFmap
DOF map.
double * _solution
Solution vector.
double * _residual
Residual vector.
double * _source
Source vector.
double * _h
Mesh spacing.
double * _solutionPrev
double _convRInfTol
int _maxIters
std::map< DOFObj, double > _bdryFlux
Detailed Description
LocalMOC Solver.
Still under active development
Definition at line 30 of file solverregmoc.h.
Constructor & Destructor Documentation
SolverRegMOC::SolverRegMOC (TransportProblem & tp)
Definition at line 5 of file solverregmoc.cpp.
References _calculateSphericalQuadrature(), _cellFlux, _mapDOFs(), SolverBase::_numDOF, _numPhaseSpaceDOF, SolverBase::_numSpaceDOF, SolverBase::_prob, SolverBase::_residual, SolverBase::_solution, SolverBase::_solutionPrev, SolverBase::_source, LOG_DBG, LOG_ERR, TransportProblem::mesh, mesh, TransportProblem::numCells, TransportProblem::numEdges, TransportProblem::numGroups, and TransportProblem::quadOrder.
SolverRegMOC::~SolverRegMOC ()
Definition at line 41 of file solverregmoc.cpp.
References _cellFlux, SolverBase::_residual, SolverBase::_solution, SolverBase::_solutionPrev, and SolverBase::_source.
Member Function Documentation
void SolverRegMOC::_addScatterSource () private
Definition at line 863 of file solverregmoc.cpp.
References _dofIndexPS(), SolverBase::_prob, SolverBase::_source, MoabMesh::getElementMat(), Material::getSigma_s(), getSubCellScalarFlux(), mesh, TransportProblem::numCells, TransportProblem::numGroups, and TransportProblem::quadOrder.
Referenced by _calculateSource().
void SolverRegMOC::_applyBoundaryConditions () private
Definition at line 593 of file solverregmoc.cpp.
References SolverBase::_bdryFlux, _dofIndex(), _getReflectedDirection(), _getTriangleOrientation(), _mu, SolverBase::_prob, SolverBase::_solution, _theta, MoabMesh::boundaryElements, TriangleDescriptorReg::edgeNeighbor, MoabMesh::getCurrentElementFromID(), MoabMesh::getEdgeID(), TransportProblem::globalBC, mesh, norm(), TransportProblem::numGroups, TransportProblem::nxnyq, reflecting, source, vacuum, TriangleDescriptorReg::vertexNeighbor1, TriangleDescriptorReg::vertexNeighbor2, UltraLightElement::x, and UltraLightElement::y.
Referenced by solve().
void SolverRegMOC::_calculateMatrixAction (double * x, double * y) private virtual
Implements SolverBase.
Definition at line 885 of file solverregmoc.cpp.
void SolverRegMOC::_calculateSource (double * fissionFlux) private
Definition at line 830 of file solverregmoc.cpp.
References _addScatterSource(), and _getExternalSource().
Referenced by solve().
void SolverRegMOC::_calculateSphericalQuadrature () private
Get spherical representation of ordinates.
Calculate (theta, mu) coordinates from the input (omega_x, omega_y, omega_z). Also get the mapping between each ordinate, u, and its negative, -v. Currently only two-dimensional problems are assumed, so the polar cosine, mu, is assumed symmetric about the xy-plane.
Definition at line 76 of file solverregmoc.cpp.
References _getAngleFromVector(), _mu, _negDir, SolverBase::_prob, _theta, LOG_ERR, TransportProblem::omega_x, TransportProblem::omega_y, TransportProblem::omega_z, pi, and TransportProblem::quadOrder.
Referenced by SolverRegMOC().
long SolverRegMOC::_dofIndex (long i, int n, int g, int edgeLoc = 0) inline private
Definition at line 40 of file solverregmoc.h.
References SolverBase::_prob, TransportProblem::numGroups, and TransportProblem::quadOrder.
Referenced by _applyBoundaryConditions(), _mapDOFs(), _sweep(), triangleSolveA(), and triangleSolveB().
long SolverRegMOC::_dofIndexPS (long i, int n, int g, int subCell = 0) inline private
Definition at line 42 of file solverregmoc.h.
References SolverBase::_prob, TransportProblem::numGroups, and TransportProblem::quadOrder.
Referenced by _addScatterSource(), _getExternalSource(), getSubCellScalarFlux(), triangleSolveA(), and triangleSolveB().
double SolverRegMOC::_getAngleFromVector (double dx, double dy) private
Calculate the azimuthal angle of a vector with components dx and dy.
Definition at line 810 of file solverregmoc.cpp.
References pi.
Referenced by _calculateSphericalQuadrature(), _getReflectedDirection(), and _getTriangleOrientation().
void SolverRegMOC::_getExternalSource () private
Definition at line 840 of file solverregmoc.cpp.
References _dofIndexPS(), _numPhaseSpaceDOF, SolverBase::_prob, SolverBase::_source, TransportProblem::getExtSource(), SourceConfiguration::hasExternalSource, TransportProblem::numCells, TransportProblem::numGroups, TransportProblem::quadOrder, SolverBase::sourceConfig, and SolverBase::sourceScaling.
Referenced by _calculateSource().
int SolverRegMOC::_getReflectedDirection (int i, double nx, double ny, double & OmegaDotn) private
Definition at line 108 of file solverregmoc.cpp.
References _getAngleFromVector(), _mu, SolverBase::_prob, _theta, LOG_DBG, LOG_ERR, and TransportProblem::quadOrder.
Referenced by _applyBoundaryConditions().
void SolverRegMOC::_getTriangleOrientation (UltraLightElement & element2, int & n, TriangleDescriptorReg & tri, int & blockID, double & theta, int & v0, int & v1, int & v2) private
Definition at line 361 of file solverregmoc.cpp.
References _getAngleFromVector(), _theta, TriangleDescriptorReg::d01, TriangleDescriptorReg::d12, TriangleDescriptorReg::d20, TriangleDescriptorReg::edge01, TriangleDescriptorReg::edge12, TriangleDescriptorReg::edge20, TriangleDescriptorReg::edgeNeighbor, TriangleDescriptorReg::i0, TriangleDescriptorReg::i1, TriangleDescriptorReg::i2, TriangleDescriptorReg::i3, UltraLightElement::neighborID, norm(), pi, TriangleDescriptorReg::theta0, TriangleDescriptorReg::theta1, TriangleDescriptorReg::theta2, TriangleDescriptorReg::vertexNeighbor1, TriangleDescriptorReg::vertexNeighbor2, UltraLightElement::x, UltraLightElement::y, and UltraLightElement::z.
Referenced by _applyBoundaryConditions(), and _sweep().
void SolverRegMOC::_mapDOFs () private virtual
Map degrees-of-freedom.
Implements SolverBase.
Definition at line 52 of file solverregmoc.cpp.
References _dofIndex(), SolverBase::_numDOF, SolverBase::_prob, SolverBase::_solution, SolverBase::DOFlist, SolverBase::DOFmap, TransportProblem::numGroups, TransportProblem::numNodes, and TransportProblem::quadOrder.
Referenced by SolverRegMOC().
void SolverRegMOC::_sweep (int n) private
Mesh sweep.
This function sweeps the mesh in the order in which the elements are listed in memory–essentially arbitray.
A MoabMesh must be used.
Definition at line 187 of file solverregmoc.cpp.
References SolverBase::_bdryFlux, _dofIndex(), _getTriangleOrientation(), _mu, SolverBase::_prob, SolverBase::_solution, _theta, TriangleDescriptorReg::edgeNeighbor, MoabMesh::getCurrentElementFromID(), MoabMesh::getEdgeID(), MoabMesh::getElementMat(), Sweeper::getNextElementID(), Material::getSigma_t(), mesh, TransportProblem::numGroups, TriangleDescriptorReg::psi0, TriangleDescriptorReg::psi1, TriangleDescriptorReg::psi4, TriangleDescriptorReg::psi5, TriangleDescriptorReg::sigma, triangleSolveA(), triangleSolveB(), TriangleDescriptorReg::vertexNeighbor1, and TriangleDescriptorReg::vertexNeighbor2.
Referenced by solve().
double* SolverRegMOC::getResidual ()
double SolverRegMOC::getScalarFlux (long space_i, int group_g) virtual
Implements SolverBase.
Definition at line 890 of file solverregmoc.cpp.
References getSubCellScalarFlux().
double SolverRegMOC::getSubCellScalarFlux (long space_i, int group_g, int subCell) private
Definition at line 902 of file solverregmoc.cpp.
References _cellFlux, _dofIndexPS(), SolverBase::_prob, TransportProblem::quadOrder, and TransportProblem::weights.
Referenced by _addScatterSource(), and getScalarFlux().
void SolverRegMOC::solve () virtual
Implementation of the LocalMOC solver.
Implements SolverBase.
Definition at line 138 of file solverregmoc.cpp.
References _applyBoundaryConditions(), _calculateSource(), SolverBase::_convRInfTol, SolverBase::_maxIters, SolverBase::_prob, SolverBase::_saveOldSolution(), SolverBase::_solution, SolverBase::_solutionPrev, _sweep(), SolverBase::calculateRInfSolutionNorm(), SolverBase::copySolution(), SourceConfiguration::hasFissionSource, SolverBase::printIterStatus(), TransportProblem::quadOrder, and SolverBase::sourceConfig.
void SolverRegMOC::triangleSolveA (TriangleDescriptorReg & tri, double & phi, double & theta, double & mu, long & elementID, int & n, int & g) private
Definition at line 955 of file solverregmoc.cpp.
References _cellFlux, _dofIndex(), _dofIndexPS(), SolverBase::_solution, SolverBase::_source, TriangleDescriptorReg::cell0, TriangleDescriptorReg::cell1, TriangleDescriptorReg::cell2, TriangleDescriptorReg::cell3, TriangleDescriptorReg::d01, TriangleDescriptorReg::d12, TriangleDescriptorReg::edge01, TriangleDescriptorReg::edge12, TriangleDescriptorReg::edge20, TriangleDescriptorReg::edgeNeighbor, MoabMesh::getEdgeID(), TriangleDescriptorReg::i0, TriangleDescriptorReg::i1, TriangleDescriptorReg::i2, TriangleDescriptorReg::i3, LOG_DBG, mesh, pi, TriangleDescriptorReg::psi0, TriangleDescriptorReg::psi01, TriangleDescriptorReg::psi1, TriangleDescriptorReg::psi13, TriangleDescriptorReg::psi2, TriangleDescriptorReg::psi21, TriangleDescriptorReg::psi3, TriangleDescriptorReg::psi4, TriangleDescriptorReg::psi5, TriangleDescriptorReg::sigma, TriangleDescriptorReg::theta1, triangleSolveEV(), and triangleSolveVE2().
Referenced by _sweep().
void SolverRegMOC::triangleSolveB (TriangleDescriptorReg & tri, double & phi, double & theta, double & mu, long & elementID, int & n, int & g) private
Definition at line 1075 of file solverregmoc.cpp.
References _cellFlux, _dofIndex(), _dofIndexPS(), SolverBase::_solution, SolverBase::_source, TriangleDescriptorReg::cell0, TriangleDescriptorReg::cell1, TriangleDescriptorReg::cell2, TriangleDescriptorReg::cell3, TriangleDescriptorReg::d01, TriangleDescriptorReg::d20, TriangleDescriptorReg::edge01, TriangleDescriptorReg::edge12, TriangleDescriptorReg::edge20, MoabMesh::getEdgeID(), TriangleDescriptorReg::i0, TriangleDescriptorReg::i1, TriangleDescriptorReg::i2, TriangleDescriptorReg::i3, LOG_DBG, mesh, pi, TriangleDescriptorReg::psi0, TriangleDescriptorReg::psi01, TriangleDescriptorReg::psi1, TriangleDescriptorReg::psi13, TriangleDescriptorReg::psi2, TriangleDescriptorReg::psi21, TriangleDescriptorReg::psi3, TriangleDescriptorReg::psi4, TriangleDescriptorReg::psi5, TriangleDescriptorReg::sigma, TriangleDescriptorReg::theta0, triangleSolveEV(), triangleSolveVE2(), TriangleDescriptorReg::vertexNeighbor1, and TriangleDescriptorReg::vertexNeighbor2.
Referenced by _sweep().
void SolverRegMOC::triangleSolveEV (double & q, double & S, double & sigma, double & x, double & psi1, double & psi2, double & psi20, double & psi01, double & cell, double & psiv) private
Definition at line 917 of file solverregmoc.cpp.
Referenced by triangleSolveA(), and triangleSolveB().
void SolverRegMOC::triangleSolveVE2 (double & q, double & S, double & sigma, double & w1, double & w2, double & w3, double & psi0r, double & psi0l, double & psi1, double & psi2, double & psi12, double & cell) private
Definition at line 936 of file solverregmoc.cpp.
Referenced by triangleSolveA(), and triangleSolveB().
Member Data Documentation
double* SolverRegMOC::_cellFlux private
Definition at line 54 of file solverregmoc.h.
Referenced by getSubCellScalarFlux(), SolverRegMOC(), triangleSolveA(), triangleSolveB(), and ~SolverRegMOC().
std::vector<double> SolverRegMOC::_mu private
Definition at line 48 of file solverregmoc.h.
Referenced by _applyBoundaryConditions(), _calculateSphericalQuadrature(), _getReflectedDirection(), and _sweep().
std::vector<int> SolverRegMOC::_negDir private
Definition at line 50 of file solverregmoc.h.
Referenced by _calculateSphericalQuadrature().
unsigned int SolverRegMOC::_numPhaseSpaceDOF private
Definition at line 82 of file solverregmoc.h.
Referenced by _getExternalSource(), and SolverRegMOC().
std::vector<double> SolverRegMOC::_theta private
Definition at line 49 of file solverregmoc.h.
Referenced by _applyBoundaryConditions(), _calculateSphericalQuadrature(), _getReflectedDirection(), _getTriangleOrientation(), and _sweep().
MoabMesh* SolverRegMOC::mesh private
Definition at line 52 of file solverregmoc.h.
Referenced by _addScatterSource(), _applyBoundaryConditions(), _sweep(), SolverRegMOC(), triangleSolveA(), and triangleSolveB().
The documentation for this class was generated from the following files:
include/solverregmoc.h
src/solverregmoc.cpp