Radiation Transport Code: Sweeper Class Reference
Sweeper Class Reference
Mesh sweeper.
#include <sweeper.h>
Public Member Functions
Sweeper (MoabMesh *mesh, int angle)
void startElementSweep (int angle=-1)
long getNextElementID ()
Private Member Functions
void _setupElementUL ()
Private Attributes
MoabMesh * mesh
std::vector
< moab::EntityHandle >
::const_iterator _nextElementIterator
std::vector< moab::EntityHandle > _sweepOrder
UltraLightElement _currentElementUL
moab::ErrorCode _rval
Detailed Description
Mesh sweeper.
This object will sweep a (Moab) mesh for a given angle, n. This was created to make parallel sweeps easier, i.e., make one object for each thread.
Definition at line 12 of file sweeper.h.
Constructor & Destructor Documentation
Sweeper::Sweeper (MoabMesh * mesh, int angle)
Definition at line 3 of file sweeper.cpp.
References MoabMesh::_mb, _nextElementIterator, MoabMesh::_orderedMeshSet, _sweepOrder, and mesh.
Member Function Documentation
void Sweeper::_setupElementUL () private
long Sweeper::getNextElementID ()
Definition at line 16 of file sweeper.cpp.
References MoabMesh::_mb, _nextElementIterator, _sweepOrder, and mesh.
Referenced by SolverDummy::_sweep(), SolverLocalMOC::_sweep(), and SolverRegMOC::_sweep().
void Sweeper::startElementSweep (int angle = -1)
Member Data Documentation
UltraLightElement Sweeper::_currentElementUL private
Definition at line 24 of file sweeper.h.
std::vector<moab::EntityHandle>::const_iterator Sweeper::_nextElementIterator private
Definition at line 21 of file sweeper.h.
Referenced by getNextElementID(), and Sweeper().
moab::ErrorCode Sweeper::_rval private
Definition at line 27 of file sweeper.h.
std::vector<moab::EntityHandle> Sweeper::_sweepOrder private
Definition at line 22 of file sweeper.h.
Referenced by getNextElementID(), and Sweeper().
MoabMesh* Sweeper::mesh private
Definition at line 20 of file sweeper.h.
Referenced by getNextElementID(), and Sweeper().
The documentation for this class was generated from the following files:
include/sweeper.h
src/sweeper.cpp