Radiation Transport Code: MaterialFactory Class Reference
MaterialFactory Class Reference
Factory for creating materials and keeping a list of available materials.
#include <material.h>
Public Member Functions
~MaterialFactory ()
int createMaterialsFromInput (InputParser &input)
void readNextMaterial (InputParser &input, int matNum)
Material * createNewMaterial (std::string &materialName, unsigned int block, unsigned int G, unsigned int N)
Material * getMaterial (std::string &materialName)
Material * getMaterial (unsigned int &materialID)
void list ()
Public Attributes
int numGroups
Static Public Attributes
static std::map< std::string,
Material * > _materialMap
static std::map< unsigned int,
Material * > _materialID
Detailed Description
Factory for creating materials and keeping a list of available materials.
Definition at line 92 of file material.h.
Constructor & Destructor Documentation
MaterialFactory::~MaterialFactory ()
Definition at line 138 of file material.cpp.
References _materialID, and _materialMap.
Member Function Documentation
int MaterialFactory::createMaterialsFromInput (InputParser & input)
Definition at line 150 of file material.cpp.
References InputParser::countSets(), LOG_DBG, numGroups, and readNextMaterial().
Referenced by SolutionManager::SolutionManager().
Material * MaterialFactory::createNewMaterial (std::string & materialName, unsigned int block, unsigned int G, unsigned int N)
Definition at line 241 of file material.cpp.
References _materialID, _materialMap, and getMaterial().
Referenced by readNextMaterial().
Material * MaterialFactory::getMaterial (std::string & materialName)
Definition at line 257 of file material.cpp.
References _materialMap.
Referenced by MeshFactory::createMeshFromInput(), and createNewMaterial().
Material * MaterialFactory::getMaterial (unsigned int & materialID)
Definition at line 273 of file material.cpp.
References _materialID.
void MaterialFactory::list ()
Definition at line 290 of file material.cpp.
References _materialMap.
Referenced by SolutionManager::SolutionManager().
void MaterialFactory::readNextMaterial (InputParser & input, int matNum)
Definition at line 163 of file material.cpp.
References Material::beta, Material::betaEff, createNewMaterial(), InputParser::getString(), InputParser::getVector(), Material::lambda, LOG_ERR, Material::numDelayedGroups, numGroups, Material::putFissionSpectrum(), Material::putNeutronSpeed(), Material::putNuSigma_f(), Material::putSigma_s(), and Material::putSigma_t().
Referenced by createMaterialsFromInput().
Member Data Documentation
std::map< unsigned int, Material * > MaterialFactory::_materialID static
Definition at line 106 of file material.h.
Referenced by createNewMaterial(), getMaterial(), and ~MaterialFactory().
std::map< std::string, Material * > MaterialFactory::_materialMap static
Definition at line 105 of file material.h.
Referenced by createNewMaterial(), Transient_NDAdaptive::execute(), Transient_UTS::execute(), getMaterial(), list(), and ~MaterialFactory().
int MaterialFactory::numGroups
Definition at line 103 of file material.h.
Referenced by createMaterialsFromInput(), and readNextMaterial().
The documentation for this class was generated from the following files:
include/material.h
src/material.cpp