Radiation Transport Code: Output Class Reference
Output Class Reference
Output object, currently supporting HDF5 and ASCII output.
#include <output.h>
Public Types
enum OutputFormat { ASCII =1, HDF5 =2, MESH =4 }
Public Member Functions
Output (std::string fileName, int format=ASCII)
~Output ()
template<class T >
void writeData (std::string varName, T *data, int size)
void registerStreamingOutput (std::string varName)
void streamOutput (std::string varName, double datum)
std::string getName ()
Public Attributes
int outputFormat
Private Member Functions
void _createStructure ()
Private Attributes
std::string outputFileName
std::ofstream outputFile
HDF5Interface hdf
int solutionPoint
std::map< std::string,
HDF5StreamableArray * > _listStreamables
Detailed Description
Output object, currently supporting HDF5 and ASCII output.
Definition at line 11 of file output.h.
Member Enumeration Documentation
enum Output::OutputFormat
Enumerator
ASCII
HDF5
MESH
Definition at line 14 of file output.h.
Constructor & Destructor Documentation
Output::Output (std::string fileName, int format = ASCII)
Definition at line 6 of file output.cpp.
References _createStructure(), ASCII, hdf, HDF5, HDF5Interface::open(), outputFile, and outputFileName.
Output::~Output ()
Definition at line 18 of file output.cpp.
References _listStreamables, ASCII, HDF5Interface::close(), hdf, HDF5, outputFile, outputFileName, and outputFormat.
Member Function Documentation
void Output::_createStructure () private
Definition at line 61 of file output.cpp.
References HDF5Interface::createDataGroup(), hdf, and outputFileName.
Referenced by Output().
std::string Output::getName ()
Definition at line 54 of file output.cpp.
References outputFileName.
Referenced by MoabMesh::writeMesh().
void Output::registerStreamingOutput (std::string varName)
Definition at line 36 of file output.cpp.
References _listStreamables, HDF5, outputFileName, and outputFormat.
Referenced by Transient::Transient(), and Transient_NDAdaptive::Transient_NDAdaptive().
void Output::streamOutput (std::string varName, double datum)
Definition at line 46 of file output.cpp.
References _listStreamables, HDF5, and outputFormat.
Referenced by Transient_NDAdaptive::execute(), Transient_UTS::execute(), and Transient::Transient().
template<class T > void Output::writeData (std::string varName, T * data, int size) inline
Definition at line 21 of file output.h.
References hdf, HDF5, outputFileName, outputFormat, and HDF5Interface::writeData().
Referenced by Mesh::writeMesh(), and SolverBase::writeSolution().
Member Data Documentation
std::map<std::string, HDF5StreamableArray*> Output::_listStreamables private
Definition at line 41 of file output.h.
Referenced by registerStreamingOutput(), streamOutput(), and ~Output().
HDF5Interface Output::hdf private
Definition at line 37 of file output.h.
Referenced by _createStructure(), Output(), writeData(), and ~Output().
std::ofstream Output::outputFile private
Definition at line 36 of file output.h.
Referenced by Output(), and ~Output().
std::string Output::outputFileName private
Definition at line 35 of file output.h.
Referenced by _createStructure(), getName(), Output(), registerStreamingOutput(), writeData(), and ~Output().
int Output::outputFormat
Definition at line 15 of file output.h.
Referenced by registerStreamingOutput(), streamOutput(), writeData(), SolverBase::writeScalarFlux(), and ~Output().
int Output::solutionPoint private
Definition at line 39 of file output.h.
The documentation for this class was generated from the following files:
include/output.h
src/output.cpp