Radiation Transport Code: HDF5Interface Class Reference
HDF5Interface Class Reference
Interface class for HDF5 file I/O.
#include <hdf5interface.h>
Public Member Functions
void open (const std::string &fileName, char mode= 'W')
void close (const std::string &filename)
void createDataGroup (const std::string &fileName, const std::string groupName)
template<class T >
void writeData (const std::string &fileName, const std::string &varName, T *data, long size)
void writeData (const std::string &fileName, const std::string &varName, const std::vector< double > &data)
HDFData * readData (const std::string &fileName, const std::string &varName)
Private Member Functions
void _createAndWrite (H5::H5File *file, H5::DataSpace &dataspace, const std::string &varName, double *data)
void _createAndWrite (H5::H5File *file, H5::DataSpace &dataspace, const std::string &varName, int *data)
void _createAndWrite (H5::H5File *file, H5::DataSpace &dataspace, const std::string &varName, long *data)
H5::H5File * _getFile (const std::string &fileName)
Static Private Attributes
static std::map< std::string,
H5::H5File * > _fileList
Map of file names to file pointers.
Friends
class HDF5StreamableArray
Detailed Description
Interface class for HDF5 file I/O.
This class provides basic functionality for reading and writing HDF5 files.
Definition at line 54 of file hdf5interface.h.
Member Function Documentation
void HDF5Interface::_createAndWrite (H5::H5File * file, H5::DataSpace & dataspace, const std::string & varName, double * data) inline private
Definition at line 88 of file hdf5interface.h.
Referenced by writeData().
void HDF5Interface::_createAndWrite (H5::H5File * file, H5::DataSpace & dataspace, const std::string & varName, int * data) inline private
Definition at line 92 of file hdf5interface.h.
void HDF5Interface::_createAndWrite (H5::H5File * file, H5::DataSpace & dataspace, const std::string & varName, long * data) inline private
Definition at line 96 of file hdf5interface.h.
H5::H5File * HDF5Interface::_getFile (const std::string & fileName) private
Definition at line 125 of file hdf5interface.cpp.
References _fileList.
Referenced by createDataGroup(), HDF5StreamableArray::HDF5StreamableArray(), open(), readData(), and writeData().
void HDF5Interface::close (const std::string & filename)
Definition at line 31 of file hdf5interface.cpp.
References _fileList.
Referenced by MeshFactory::createMeshFromInput(), MoabMesh::readMeshSweepOrder(), Transient::Transient(), and Output::~Output().
void HDF5Interface::createDataGroup (const std::string & fileName, const std::string groupName)
Definition at line 46 of file hdf5interface.cpp.
References _getFile().
Referenced by Output::_createStructure().
void HDF5Interface::open (const std::string & fileName, char mode = 'W')
Definition at line 9 of file hdf5interface.cpp.
References _fileList, and _getFile().
Referenced by MeshFactory::createMeshFromInput(), Output::Output(), MoabMesh::readMeshSweepOrder(), Transient::Transient(), and TransportProblem::TransportProblem().
HDFData * HDF5Interface::readData (const std::string & fileName, const std::string & varName)
Definition at line 81 of file hdf5interface.cpp.
References _getFile(), HDFData::data, HDFData::dims, and HDFData::rank.
Referenced by MeshFactory::createMeshFromInput(), MoabMesh::readMeshSweepOrder(), Transient::Transient(), and TransportProblem::TransportProblem().
template<class T > void HDF5Interface::writeData (const std::string & fileName, const std::string & varName, T * data, long size) inline
Definition at line 65 of file hdf5interface.h.
References _createAndWrite(), and _getFile().
Referenced by Output::writeData(), and writeData().
void HDF5Interface::writeData (const std::string & fileName, const std::string & varName, const std::vector< double > & data)
Write a 1D vector of doubles to file
Definition at line 61 of file hdf5interface.cpp.
References writeData().
Friends And Related Function Documentation
friend class HDF5StreamableArray friend
Definition at line 56 of file hdf5interface.h.
Member Data Documentation
std::map< std::string, H5::H5File * > HDF5Interface::_fileList static private
Map of file names to file pointers.
Definition at line 102 of file hdf5interface.h.
Referenced by _getFile(), close(), and open().
The documentation for this class was generated from the following files:
include/hdf5interface.h
src/hdf5interface.cpp