Radiation Transport Code: FixedSource Class Reference
FixedSource Class Reference
Fixed source solution manager.
#include <fixedsource.h>
Public Member Functions
FixedSource (InputParser &input)
~FixedSource ()
void execute ()
Public Member Functions inherited from SolutionManager
virtual ~SolutionManager ()
Private Member Functions
void _saveSolutionState ()
Additional Inherited Members
Public Types inherited from SolutionManager
enum ProblemType { FixedSource, Eigenvalue, Transient }
Public Attributes inherited from SolutionManager
enum SolutionManager::ProblemType problemType
Protected Member Functions inherited from SolutionManager
SolutionManager (ProblemType problemType, InputParser &input)
Protected Attributes inherited from SolutionManager
MaterialFactory materialFactory
MeshFactory meshFactory
TransportProblem * _transportProblem
SolverBase * solver
InputParser & _input
Output * _output
Detailed Description
Fixed source solution manager.
Solve a fixed source problem.
Definition at line 10 of file fixedsource.h.
Constructor & Destructor Documentation
FixedSource::FixedSource (InputParser & input)
Definition at line 5 of file fixedsource.cpp.
References SourceConfiguration::hasExternalSource, SourceConfiguration::hasFissionSource, SourceConfiguration::hasScatterSource, SourceConfiguration::hasTransientSource, SolutionManager::solver, and SolverBase::sourceConfig.
FixedSource::~FixedSource ()
Definition at line 14 of file fixedsource.cpp.
Member Function Documentation
void FixedSource::_saveSolutionState () private virtual
Implements SolutionManager.
Definition at line 32 of file fixedsource.cpp.
References SolutionManager::_output, SolutionManager::solver, SolverBase::writeScalarFlux(), and SolverBase::writeSolution().
Referenced by execute().
void FixedSource::execute () virtual
Implements SolutionManager.
Definition at line 19 of file fixedsource.cpp.
References _saveSolutionState(), SolutionManager::_transportProblem, TransportProblem::hasFixedSource, LOG_ERR, SolverBase::solve(), and SolutionManager::solver.
The documentation for this class was generated from the following files:
include/fixedsource.h
src/fixedsource.cpp