Radiation Transport Code: Transient Class Reference
Transient Class Reference abstract
Transient solution manager.
#include <transient.h>
Public Member Functions
Transient (InputParser &input)
virtual ~Transient ()
Public Member Functions inherited from SolutionManager
virtual ~SolutionManager ()
virtual void execute ()=0
Protected Member Functions
void _pushBackSolution ()
void _calculateEquilibriumPrecs ()
void _updateDelayedNeutronPrecs ()
void _saveSolutionState ()
void _calculateTransientSource ()
virtual double _getTimeStep ()=0
Protected Member Functions inherited from SolutionManager
SolutionManager (ProblemType problemType, InputParser &input)
Protected Attributes
double * prevTimeSolution
double * prevPrevTimeSolution
double _tMax
double _dt
double _criticalEigenvalue
int numDelayedGroups
double * delayedNeutronPrec
Protected Attributes inherited from SolutionManager
MaterialFactory materialFactory
MeshFactory meshFactory
TransportProblem * _transportProblem
SolverBase * solver
InputParser & _input
Output * _output
Additional Inherited Members
Public Types inherited from SolutionManager
enum ProblemType { FixedSource, Eigenvalue, Transient }
Public Attributes inherited from SolutionManager
enum SolutionManager::ProblemType problemType
Detailed Description
Transient solution manager.
Solve a transient problem
Definition at line 10 of file transient.h.
Constructor & Destructor Documentation
Transient::Transient (InputParser & input)
Definition at line 11 of file transient.cpp.
References _calculateEquilibriumPrecs(), _criticalEigenvalue, _dt, SolutionManager::_output, _tMax, SolutionManager::_transportProblem, HDFDataStruct< T >::clear(), HDF5Interface::close(), HDFDataStruct< T >::data, delayedNeutronPrec, HDFData::dims, HDFDataStruct< T >::getData(), SolverBase::getNumDOFs(), InputParser::getString(), SolverBase::getTotalNeutronProduction(), InputParser::getVector(), SourceConfiguration::hasExternalSource, SourceConfiguration::hasFissionSource, TransportProblem::hasFixedSource, SourceConfiguration::hasScatterSource, SourceConfiguration::hasTransientSource, LOG, LOG_ERR, LOG_WARN, SolverBase::normalizeSolution(), TransportProblem::numCells, numDelayedGroups, HDF5Interface::open(), HDF5Interface::readData(), Output::registerStreamingOutput(), SolverBase::setSolution(), SolutionManager::solver, SolverBase::sourceConfig, SolverBase::sourceScaling, Output::streamOutput(), and SolverBase::zeroSolution().
Transient::~Transient () virtual
Definition at line 82 of file transient.cpp.
Member Function Documentation
void Transient::_calculateEquilibriumPrecs () protected
Definition at line 95 of file transient.cpp.
References _criticalEigenvalue, SolutionManager::_transportProblem, Material::beta, delayedNeutronPrec, MeshInterface::getElementMat(), SolverBase::getNeutronProduction(), Material::lambda, TransportProblem::mesh, TransportProblem::numCells, numDelayedGroups, and SolutionManager::solver.
Referenced by Transient().
void Transient::_calculateTransientSource () protected
Definition at line 145 of file transient.cpp.
References _dt, Material::_speed, SolutionManager::_transportProblem, Material::beta, delayedNeutronPrec, MeshInterface::getElementMat(), Material::getFissionSpectrum(), SolverBase::getSolutionValue(), Material::lambda, TransportProblem::mesh, TransportProblem::numCells, numDelayedGroups, TransportProblem::numGroups, TransportProblem::putExtSource(), TransportProblem::quadOrder, and SolutionManager::solver.
Referenced by Transient_NDAdaptive::execute(), and Transient_UTS::execute().
virtual double Transient::_getTimeStep () protected pure virtual
Implemented in Transient_NDAdaptive, and Transient_UTS.
void Transient::_pushBackSolution () protected
Definition at line 88 of file transient.cpp.
References SolverBase::copySolution(), prevTimeSolution, and SolutionManager::solver.
Referenced by Transient_UTS::execute(), and Transient_UTS::Transient_UTS().
void Transient::_saveSolutionState () protected virtual
Implements SolutionManager.
Definition at line 137 of file transient.cpp.
References SolutionManager::_output, SolutionManager::solver, SolverBase::writeScalarFlux(), and SolverBase::writeSolution().
Referenced by Transient_NDAdaptive::execute(), and Transient_UTS::execute().
void Transient::_updateDelayedNeutronPrecs () protected
Definition at line 117 of file transient.cpp.
References _criticalEigenvalue, _dt, SolutionManager::_transportProblem, Material::beta, delayedNeutronPrec, MeshInterface::getElementMat(), SolverBase::getNeutronProduction(), Material::lambda, TransportProblem::mesh, TransportProblem::numCells, numDelayedGroups, and SolutionManager::solver.
Referenced by Transient_NDAdaptive::execute(), and Transient_UTS::execute().
Member Data Documentation
double Transient::_criticalEigenvalue protected
Definition at line 30 of file transient.h.
Referenced by _calculateEquilibriumPrecs(), _updateDelayedNeutronPrecs(), Transient_NDAdaptive::execute(), Transient_UTS::execute(), and Transient().
double Transient::_dt protected
Definition at line 29 of file transient.h.
Referenced by _calculateTransientSource(), Transient_NDAdaptive::_estimateSecondDerivative(), Transient_UTS::_getTimeStep(), Transient_NDAdaptive::_pushBackSolution(), _updateDelayedNeutronPrecs(), Transient_UTS::execute(), Transient_NDAdaptive::execute(), and Transient().
double Transient::_tMax protected
Definition at line 28 of file transient.h.
Referenced by Transient_NDAdaptive::execute(), Transient_UTS::execute(), and Transient().
double* Transient::delayedNeutronPrec protected
Definition at line 33 of file transient.h.
Referenced by _calculateEquilibriumPrecs(), _calculateTransientSource(), _updateDelayedNeutronPrecs(), Transient_UTS::execute(), Transient_NDAdaptive::execute(), and Transient().
int Transient::numDelayedGroups protected
Definition at line 32 of file transient.h.
Referenced by _calculateEquilibriumPrecs(), _calculateTransientSource(), _updateDelayedNeutronPrecs(), Transient_UTS::execute(), Transient_NDAdaptive::execute(), and Transient().
double* Transient::prevPrevTimeSolution protected
Definition at line 26 of file transient.h.
Referenced by Transient_NDAdaptive::_estimateSecondDerivative(), and Transient_NDAdaptive::_pushBackSolution().
double* Transient::prevTimeSolution protected
Definition at line 25 of file transient.h.
Referenced by Transient_NDAdaptive::_estimateSecondDerivative(), Transient_NDAdaptive::_pushBackSolution(), _pushBackSolution(), Transient_NDAdaptive::execute(), and Transient_UTS::execute().
The documentation for this class was generated from the following files:
include/transient.h
src/transient.cpp