Radiation Transport Code: DAG Class Reference
DAG Class Reference
#include <dag.h>
Public Member Functions
DAG ()
~DAG ()
void addVertex (long id)
void addEdge (long parentID, long childID)
void removeEdge (long parentID, long childID)
void getRoots ()
void orderVertices ()
Private Attributes
std::map< long, Vertex * > vertexList
std::deque< long > roots
std::deque< long > orderedVertices
Detailed Description
Definition at line 9 of file dag.h.
Constructor & Destructor Documentation
DAG::DAG ()
DAG::~DAG ()
Member Function Documentation
void DAG::addEdge (long parentID, long childID)
Definition at line 4 of file dag.cpp.
References addVertex(), and vertexList.
void DAG::addVertex (long id) inline
Definition at line 15 of file dag.h.
References vertexList.
Referenced by addEdge().
void DAG::getRoots ()
Definition at line 18 of file dag.cpp.
References roots, and vertexList.
Referenced by orderVertices().
void DAG::orderVertices ()
Definition at line 27 of file dag.cpp.
References getRoots(), orderedVertices, removeEdge(), roots, and vertexList.
void DAG::removeEdge (long parentID, long childID)
Definition at line 12 of file dag.cpp.
References vertexList.
Referenced by orderVertices().
Member Data Documentation
std::deque<long> DAG::orderedVertices private
Definition at line 24 of file dag.h.
Referenced by orderVertices().
std::deque<long> DAG::roots private
Definition at line 23 of file dag.h.
Referenced by getRoots(), and orderVertices().
std::map<long,Vertex*> DAG::vertexList private
Definition at line 22 of file dag.h.
Referenced by addEdge(), addVertex(), getRoots(), orderVertices(), and removeEdge().
The documentation for this class was generated from the following files:
include/dag.h
src/dag.cpp