Radiation Transport Code: Transient_UTS Class Reference
Transient_UTS Class Reference
Transient solution manager with unform time steps.
#include <transient_uts.h>
Public Member Functions
Transient_UTS (InputParser &input)
~Transient_UTS ()
void execute ()
Public Member Functions inherited from Transient
Transient (InputParser &input)
virtual ~Transient ()
Public Member Functions inherited from SolutionManager
virtual ~SolutionManager ()
Private Member Functions
double _getTimeStep ()
Additional Inherited Members
Public Types inherited from SolutionManager
enum ProblemType { FixedSource, Eigenvalue, Transient }
Public Attributes inherited from SolutionManager
enum SolutionManager::ProblemType problemType
Protected Member Functions inherited from Transient
void _pushBackSolution ()
void _calculateEquilibriumPrecs ()
void _updateDelayedNeutronPrecs ()
void _saveSolutionState ()
void _calculateTransientSource ()
Protected Member Functions inherited from SolutionManager
SolutionManager (ProblemType problemType, InputParser &input)
Protected Attributes inherited from Transient
double * prevTimeSolution
double * prevPrevTimeSolution
double _tMax
double _dt
double _criticalEigenvalue
int numDelayedGroups
double * delayedNeutronPrec
Protected Attributes inherited from SolutionManager
MaterialFactory materialFactory
MeshFactory meshFactory
TransportProblem * _transportProblem
SolverBase * solver
InputParser & _input
Output * _output
Detailed Description
Transient solution manager with unform time steps.
Definition at line 7 of file transient_uts.h.
Constructor & Destructor Documentation
Transient_UTS::Transient_UTS (InputParser & input)
Definition at line 6 of file transient_uts.cpp.
References Transient::_pushBackSolution().
Transient_UTS::~Transient_UTS ()
Definition at line 12 of file transient_uts.cpp.
Member Function Documentation
double Transient_UTS::_getTimeStep () private virtual
Implements Transient.
Definition at line 75 of file transient_uts.cpp.
References Transient::_dt.
Referenced by execute().
void Transient_UTS::execute () virtual
Implements SolutionManager.
Definition at line 17 of file transient_uts.cpp.
References Transient::_calculateTransientSource(), Transient::_criticalEigenvalue, Transient::_dt, _getTimeStep(), MaterialFactory::_materialMap, Material::_nu_sigma_f_scaling, SolutionManager::_output, Transient::_pushBackSolution(), Transient::_saveSolutionState(), Material::_sigma_t_adder, Material::_speed, Transient::_tMax, SolutionManager::_transportProblem, Transient::_updateDelayedNeutronPrecs(), Material::beta, Material::betaEff, Transient::delayedNeutronPrec, SolverBase::getTotalNeutronProduction(), Material::lambda, LOG, Transient::numDelayedGroups, TransportProblem::numGroups, Transient::prevTimeSolution, SolverBase::solve(), SolutionManager::solver, and Output::streamOutput().
The documentation for this class was generated from the following files:
include/transient_uts.h
src/transient_uts.cpp