Radiation Transport Code: PerfStats Class Reference
PerfStats Class Reference
Collect performance statistics.
#include <perfstats.h>
Public Member Functions
PerfStats (std::string const obj)
~PerfStats ()
Static Public Member Functions
static void display ()
Static Public Attributes
static std::map< std::string,
double > wallTime
static std::map< std::string,
double > cpuTime
static std::map< std::string, int > count
Static Private Member Functions
static void _print (const std::string &obj, const double &time, const std::string &units)
Private Attributes
std::string objectName
double _wallTimeStart
double _cpuTimeStart
Detailed Description
Collect performance statistics.
Collect wall and cpu time measurements for the life of this object.
Definition at line 14 of file perfstats.h.
Constructor & Destructor Documentation
PerfStats::PerfStats (std::string const obj) inline
Definition at line 17 of file perfstats.h.
References _cpuTimeStart, _wallTimeStart, Timing::get_cpu_time(), Timing::get_wall_time(), and objectName.
PerfStats::~PerfStats () inline
Definition at line 24 of file perfstats.h.
References _cpuTimeStart, _wallTimeStart, count, cpuTime, Timing::get_cpu_time(), Timing::get_wall_time(), objectName, and wallTime.
Member Function Documentation
void PerfStats::_print (const std::string & obj, const double & time, const std::string & units) static private
Definition at line 33 of file perfstats.cpp.
Referenced by display().
void PerfStats::display () static
Definition at line 12 of file perfstats.cpp.
References _print(), count, cpuTime, and wallTime.
Referenced by main().
Member Data Documentation
double PerfStats::_cpuTimeStart private
Definition at line 41 of file perfstats.h.
Referenced by PerfStats(), and ~PerfStats().
double PerfStats::_wallTimeStart private
Definition at line 40 of file perfstats.h.
Referenced by PerfStats(), and ~PerfStats().
std::map< std::string, int > PerfStats::count static
Definition at line 35 of file perfstats.h.
Referenced by display(), and ~PerfStats().
std::map< std::string, double > PerfStats::cpuTime static
Definition at line 34 of file perfstats.h.
Referenced by display(), and ~PerfStats().
std::string PerfStats::objectName private
Definition at line 38 of file perfstats.h.
Referenced by PerfStats(), and ~PerfStats().
std::map< std::string, double > PerfStats::wallTime static
Definition at line 33 of file perfstats.h.
Referenced by display(), and ~PerfStats().
The documentation for this class was generated from the following files:
include/perfstats.h
src/perfstats.cpp