Radiation Transport Code: MeshInterface Class Reference
MeshInterface Class Reference abstract
Virual mesh interface.
#include <meshinterface.h>
Public Member Functions
MeshInterface ()
virtual ~MeshInterface ()
virtual void loadMesh (std::string inputFileName)=0
virtual void writeMesh (Output *outputFile)=0
virtual void tagMesh (std::string tagName, double *tagDataBuffer, long tagSize)=0
virtual Element * getElement (long elemID)=0
virtual double getElementVolume (long elemID)=0
virtual Material * getElementMat (long elemID)=0
long numNodes ()
long numEdges ()
long numElements ()
int dim ()
virtual void readMeshSweepOrder (const std::string fileName)=0
virtual void createDefaultMeshSweepOrder ()=0
Protected Attributes
int _dimension
long _numNodes
long _numEdges
long _numElements
Detailed Description
Virual mesh interface.
Definition at line 11 of file meshinterface.h.
Constructor & Destructor Documentation
MeshInterface::MeshInterface () inline
Definition at line 14 of file meshinterface.h.
virtual MeshInterface::~MeshInterface () inline virtual
Definition at line 15 of file meshinterface.h.
Member Function Documentation
virtual void MeshInterface::createDefaultMeshSweepOrder () pure virtual
Implemented in MoabMesh, and Mesh.
Referenced by MeshFactory::createMeshFromInput().
int MeshInterface::dim () inline
Definition at line 29 of file meshinterface.h.
References _dimension.
virtual Element* MeshInterface::getElement (long elemID) pure virtual
Implemented in Mesh, and MoabMesh.
Referenced by MeshFactory::createMeshFromInput().
virtual Material* MeshInterface::getElementMat (long elemID) pure virtual
Implemented in Mesh, and MoabMesh.
Referenced by Transient::_calculateEquilibriumPrecs(), Transient::_calculateTransientSource(), Transient::_updateDelayedNeutronPrecs(), SolverBase::getNeutronProduction(), and SolverBase::getTotalNeutronProduction().
virtual double MeshInterface::getElementVolume (long elemID) pure virtual
Implemented in MoabMesh, and Mesh.
Referenced by SolverBase::getTotalNeutronProduction().
virtual void MeshInterface::loadMesh (std::string inputFileName) pure virtual
Implemented in MoabMesh, and Mesh.
Referenced by MeshFactory::createMeshFromInput().
long MeshInterface::numEdges () inline
Definition at line 27 of file meshinterface.h.
References _numEdges.
Referenced by TransportProblem::TransportProblem().
long MeshInterface::numElements () inline
Definition at line 28 of file meshinterface.h.
References _numElements.
Referenced by MeshFactory::createMeshFromInput(), and TransportProblem::TransportProblem().
long MeshInterface::numNodes () inline
Definition at line 26 of file meshinterface.h.
References _numNodes.
Referenced by TransportProblem::TransportProblem().
virtual void MeshInterface::readMeshSweepOrder (const std::string fileName) pure virtual
Implemented in MoabMesh, and Mesh.
Referenced by MeshFactory::createMeshFromInput().
virtual void MeshInterface::tagMesh (std::string tagName, double * tagDataBuffer, long tagSize) pure virtual
Implemented in MoabMesh, and Mesh.
Referenced by SolverBase::writeScalarFlux().
virtual void MeshInterface::writeMesh (Output * outputFile) pure virtual
Implemented in MoabMesh, and Mesh.
Referenced by SolverBase::writeScalarFlux().
Member Data Documentation
int MeshInterface::_dimension protected
Definition at line 35 of file meshinterface.h.
Referenced by dim(), MoabMesh::loadMesh(), and Mesh::Mesh().
long MeshInterface::_numEdges protected
Definition at line 37 of file meshinterface.h.
Referenced by MoabMesh::loadMesh(), and numEdges().
long MeshInterface::_numElements protected
Definition at line 38 of file meshinterface.h.
Referenced by MoabMesh::loadMesh(), Mesh::make1DUniform(), numElements(), and Mesh::writeMesh().
long MeshInterface::_numNodes protected
Definition at line 36 of file meshinterface.h.
Referenced by MoabMesh::loadMesh(), Mesh::make1DUniform(), and numNodes().
The documentation for this class was generated from the following file:
include/meshinterface.h