Radiation Transport Code: SolverDummy Class Reference
SolverDummy Class Reference
LocalMOC Solver.
#include <solverdummy.h>
Public Member Functions
SolverDummy (TransportProblem &tp)
~SolverDummy ()
void solve ()
Implementation of the LocalMOC solver.
double getScalarFlux (long space_i, int group_g)
Public Member Functions inherited from SolverBase
virtual ~SolverBase ()
double calculateL2SolutionNorm (double *solutionComp)
double calculateLInfSolutionNorm (double *solutionComp)
double calculateRInfSolutionNorm (double *solutionComp)
double calculateL2SolutionError ()
double calculateRInfSolutionError ()
const double * getSolutionValue (long space_i, int quad_n, int group_g)
const double * getSolutionValue (long i)
long getNumDOFs ()
TransportProblem & getTransportProblem ()
double getNeutronProduction (long space_i)
double getTotalNeutronProduction ()
void setRInfTol (double tol)
void setMaxIters (int maxIters)
void setSolution (double *solution)
double * copySolution (double *solutionCopy)
void normalizeSolution (double totalProductionRate)
void zeroSolution ()
void extrapolateSolution (double expExtrapFactor)
void extrapolateSolution (double expExtrapFactor, double *baseSolution)
void writeSolution (Output *outputFile)
void writeScalarFlux (Output *outputFile)
void printIterStatus (std::string name, int iter, double err, double tol)
Private Member Functions
unsigned long _dofIndex (long i, int n, int g)
void _mapDOFs ()
Map degrees-of-freedom.
void _calculateSphericalQuadrature ()
Get spherical representation of ordinates.
void _sweep (int n)
Mesh sweep.
double _getAngleFromVector (double dx, double dy)
Calculate the azimuthal angle of a vector with components dx and dy.
void _calculateMatrixAction (double *x, double *y)
Private Attributes
std::vector< double > _mu
std::vector< double > _theta
std::vector< int > _negDir
MoabMesh * mesh
Additional Inherited Members
Public Attributes inherited from SolverBase
SourceConfiguration sourceConfig
double sourceScaling
This scales the external source, but is used as a fission source in the power method.
double criticalEigenvalue
"Critical" eigenvalue for transient calculations based on ICs from an eigenvalue calculation
Protected Member Functions inherited from SolverBase
SolverBase (TransportProblem &tp)
Constructor.
void _calculateResidual ()
void _saveOldSolution ()
Protected Attributes inherited from SolverBase
TransportProblem & _prob
Reference to the base transport problem.
long _numDOF
Number of DOF.
long _numSpaceDOF
Number of spatial DOF.
std::vector< DOFObj > DOFlist
List of DOF (currently unused)
std::map< DOFObj, double * > DOFmap
DOF map.
double * _solution
Solution vector.
double * _residual
Residual vector.
double * _source
Source vector.
double * _h
Mesh spacing.
double * _solutionPrev
double _convRInfTol
int _maxIters
std::map< DOFObj, double > _bdryFlux
Detailed Description
LocalMOC Solver.
Still under active development
Definition at line 12 of file solverdummy.h.
Constructor & Destructor Documentation
SolverDummy::SolverDummy (TransportProblem & tp)
Definition at line 5 of file solverdummy.cpp.
References _calculateSphericalQuadrature(), _mapDOFs(), SolverBase::_numDOF, SolverBase::_numSpaceDOF, SolverBase::_prob, LOG_DBG, LOG_ERR, TransportProblem::mesh, mesh, TransportProblem::numCells, TransportProblem::numGroups, and TransportProblem::quadOrder.
SolverDummy::~SolverDummy ()
Definition at line 24 of file solverdummy.cpp.
Member Function Documentation
void SolverDummy::_calculateMatrixAction (double * x, double * y) private virtual
Implements SolverBase.
Definition at line 285 of file solverdummy.cpp.
void SolverDummy::_calculateSphericalQuadrature () private
Get spherical representation of ordinates.
Calculate (theta, mu) coordinates from the input (omega_x, omega_y, omega_z). Also get the mapping between each ordinate, u, and its negative, -v. Currently only two-dimensional problems are assumed, so the polar cosine, mu, is assumed symmetric about the xy-plane.
Definition at line 51 of file solverdummy.cpp.
References _getAngleFromVector(), _mu, _negDir, SolverBase::_prob, _theta, LOG_ERR, TransportProblem::omega_x, TransportProblem::omega_y, TransportProblem::omega_z, pi, and TransportProblem::quadOrder.
Referenced by SolverDummy().
unsigned long SolverDummy::_dofIndex (long i, int n, int g) inline private
Definition at line 21 of file solverdummy.h.
References SolverBase::_prob, TransportProblem::numGroups, and TransportProblem::quadOrder.
double SolverDummy::_getAngleFromVector (double dx, double dy) private
Calculate the azimuthal angle of a vector with components dx and dy.
Definition at line 268 of file solverdummy.cpp.
References pi.
Referenced by _calculateSphericalQuadrature(), and _sweep().
void SolverDummy::_mapDOFs () private virtual
Map degrees-of-freedom.
Implements SolverBase.
Definition at line 30 of file solverdummy.cpp.
References SolverBase::_numDOF, SolverBase::_prob, SolverBase::DOFlist, TransportProblem::numCells, TransportProblem::numGroups, and TransportProblem::quadOrder.
Referenced by SolverDummy().
void SolverDummy::_sweep (int n) private
Mesh sweep.
A MoabMesh must be used.
Definition at line 99 of file solverdummy.cpp.
References _getAngleFromVector(), _negDir, _theta, Sweeper::getNextElementID(), mesh, UltraLightElement::neighborID, pi, UltraLightElement::vertexID, UltraLightElement::x, UltraLightElement::y, and UltraLightElement::z.
Referenced by solve().
double SolverDummy::getScalarFlux (long space_i, int group_g) virtual
Implements SolverBase.
Definition at line 290 of file solverdummy.cpp.
void SolverDummy::solve () virtual
Implementation of the LocalMOC solver.
Implements SolverBase.
Definition at line 84 of file solverdummy.cpp.
References SolverBase::_prob, _sweep(), and TransportProblem::quadOrder.
Member Data Documentation
std::vector<double> SolverDummy::_mu private
Definition at line 27 of file solverdummy.h.
Referenced by _calculateSphericalQuadrature().
std::vector<int> SolverDummy::_negDir private
Definition at line 29 of file solverdummy.h.
Referenced by _calculateSphericalQuadrature(), and _sweep().
std::vector<double> SolverDummy::_theta private
Definition at line 28 of file solverdummy.h.
Referenced by _calculateSphericalQuadrature(), and _sweep().
MoabMesh* SolverDummy::mesh private
Definition at line 31 of file solverdummy.h.
Referenced by _sweep(), and SolverDummy().
The documentation for this class was generated from the following files:
include/solverdummy.h
src/solverdummy.cpp