Radiation Transport Code: MoabMesh Class Reference
MoabMesh Class Reference
Unstructured mesh using the MOAB library.
#include <moabmesh.h>
Public Member Functions
MoabMesh ()
~MoabMesh ()
long getEdgeID (long node1, long node2)
void setElementMat (long elementID, Material *mat)
Material * getElementMat (long elementID)
long queryPointLocation (double *point)
long getAdjacentTriangle (long triangle, long vertex1, long vertex2)
void getCurrentElementFromID (long elementID, UltraLightElement &elementUL)
Element * getElement (long elemID)
void loadMesh (std::string inputFileName)
void writeMesh (Output *outputFile)
void tagMesh (std::string tagName, double *tagDataBuffer, long tagSize)
void readMeshSweepOrder (const std::string fileName)
void createDefaultMeshSweepOrder ()
double getElementVolume (long elemID)
void logMemoryUse ()
Public Member Functions inherited from MeshInterface
MeshInterface ()
virtual ~MeshInterface ()
long numNodes ()
long numEdges ()
long numElements ()
int dim ()
Public Attributes
std::vector< long > boundaryElements
Private Member Functions
void _identifyEdges ()
void _identifyBoundaryElements ()
Private Attributes
moab::Interface * _mb
std::vector< moab::EntityHandle > _orderedMeshSet
std::vector< moab::EntityHandle > _tris
moab::Range _verts
std::map< std::pair< long,
long >, long > _edgeID
std::vector< Material * > _materialList
moab::EntityHandle * _connectivity
double * _x
double * _y
double * _z
moab::ErrorCode _rval
Friends
class Sweeper
Additional Inherited Members
Protected Attributes inherited from MeshInterface
int _dimension
long _numNodes
long _numEdges
long _numElements
Detailed Description
Unstructured mesh using the MOAB library.
Definition at line 8 of file moabmesh.h.
Constructor & Destructor Documentation
MoabMesh::MoabMesh ()
Definition at line 5 of file moabmesh.cpp.
References _mb.
MoabMesh::~MoabMesh ()
Definition at line 12 of file moabmesh.cpp.
References _materialList, _mb, and logMemoryUse().
Member Function Documentation
void MoabMesh::_identifyBoundaryElements () private
Definition at line 124 of file moabmesh.cpp.
References _edgeID, _identifyEdges(), _mb, _tris, boundaryElements, and LOG_DBG.
Referenced by loadMesh().
void MoabMesh::_identifyEdges () private
Definition at line 86 of file moabmesh.cpp.
References _connectivity, _edgeID, _mb, _rval, _tris, and LOG_DBG.
Referenced by _identifyBoundaryElements(), and loadMesh().
void MoabMesh::createDefaultMeshSweepOrder () inline virtual
Implements MeshInterface.
Definition at line 34 of file moabmesh.h.
long MoabMesh::getAdjacentTriangle (long triangle, long vertex1, long vertex2)
Definition at line 306 of file moabmesh.cpp.
References _mb, and _rval.
Referenced by getCurrentElementFromID().
void MoabMesh::getCurrentElementFromID (long elementID, UltraLightElement & elementUL)
Definition at line 63 of file moabmesh.cpp.
References _connectivity, _x, _y, _z, UltraLightElement::elementID, getAdjacentTriangle(), UltraLightElement::neighborID, UltraLightElement::vertexID, UltraLightElement::x, UltraLightElement::y, and UltraLightElement::z.
Referenced by SolverLocalMOC::_applyBoundaryConditions(), SolverRegMOC::_applyBoundaryConditions(), SolverLocalMOC::_sweep(), and SolverRegMOC::_sweep().
long MoabMesh::getEdgeID (long node1, long node2)
Definition at line 141 of file moabmesh.cpp.
References _edgeID.
Referenced by SolverRegMOC::_applyBoundaryConditions(), SolverLocalMOC::_sweep(), SolverRegMOC::_sweep(), SolverRegMOC::triangleSolveA(), and SolverRegMOC::triangleSolveB().
Element* MoabMesh::getElement (long elemID) inline virtual
Implements MeshInterface.
Definition at line 27 of file moabmesh.h.
Material* MoabMesh::getElementMat (long elementID) inline virtual
Implements MeshInterface.
Definition at line 18 of file moabmesh.h.
References _materialList.
Referenced by SolverLocalMOC::_addScatterSource(), SolverRegMOC::_addScatterSource(), SolverLocalMOC::_sweep(), and SolverRegMOC::_sweep().
double MoabMesh::getElementVolume (long elemID) virtual
Implements MeshInterface.
Definition at line 322 of file moabmesh.cpp.
References _connectivity, _x, and _y.
void MoabMesh::loadMesh (std::string inputFileName) virtual
Implements MeshInterface.
Definition at line 23 of file moabmesh.cpp.
References _connectivity, MeshInterface::_dimension, _identifyBoundaryElements(), _identifyEdges(), _materialList, _mb, MeshInterface::_numEdges, MeshInterface::_numElements, MeshInterface::_numNodes, _rval, _tris, _verts, _x, _y, _z, LOG, and logMemoryUse().
void MoabMesh::logMemoryUse ()
Definition at line 283 of file moabmesh.cpp.
References _mb, and LOG.
Referenced by loadMesh(), and ~MoabMesh().
long MoabMesh::queryPointLocation (double * point)
Definition at line 188 of file moabmesh.cpp.
References _mb, _rval, and LOG_DBG.
void MoabMesh::readMeshSweepOrder (const std::string fileName) virtual
Implements MeshInterface.
Definition at line 157 of file moabmesh.cpp.
References _mb, _orderedMeshSet, HDFDataStruct< T >::clear(), HDF5Interface::close(), HDFDataStruct< T >::data, HDFData::dims, LOG, LOG_DBG, HDF5Interface::open(), and HDF5Interface::readData().
void MoabMesh::setElementMat (long elementID, Material * mat) inline
Definition at line 17 of file moabmesh.h.
References _materialList.
Referenced by MeshFactory::createMeshFromInput().
void MoabMesh::tagMesh (std::string tagName, double * tagDataBuffer, long tagSize) virtual
Implements MeshInterface.
Definition at line 259 of file moabmesh.cpp.
References _mb, _rval, _tris, _verts, LOG_DBG, and LOG_ERR.
void MoabMesh::writeMesh (Output * outputFile) virtual
Implements MeshInterface.
Definition at line 241 of file moabmesh.cpp.
References _mb, _rval, _verts, and Output::getName().
Friends And Related Function Documentation
friend class Sweeper friend
Definition at line 10 of file moabmesh.h.
Member Data Documentation
moab::EntityHandle* MoabMesh::_connectivity private
Definition at line 55 of file moabmesh.h.
Referenced by _identifyEdges(), getCurrentElementFromID(), getElementVolume(), and loadMesh().
std::map<std::pair<long, long>, long> MoabMesh::_edgeID private
Definition at line 51 of file moabmesh.h.
Referenced by _identifyBoundaryElements(), _identifyEdges(), and getEdgeID().
std::vector<Material*> MoabMesh::_materialList private
Definition at line 53 of file moabmesh.h.
Referenced by getElementMat(), loadMesh(), setElementMat(), and ~MoabMesh().
moab::Interface* MoabMesh::_mb private
Definition at line 43 of file moabmesh.h.
Referenced by _identifyBoundaryElements(), _identifyEdges(), getAdjacentTriangle(), Sweeper::getNextElementID(), loadMesh(), logMemoryUse(), MoabMesh(), queryPointLocation(), readMeshSweepOrder(), Sweeper::Sweeper(), tagMesh(), writeMesh(), and ~MoabMesh().
std::vector<moab::EntityHandle> MoabMesh::_orderedMeshSet private
Definition at line 45 of file moabmesh.h.
Referenced by readMeshSweepOrder(), and Sweeper::Sweeper().
moab::ErrorCode MoabMesh::_rval private
Definition at line 60 of file moabmesh.h.
Referenced by _identifyEdges(), getAdjacentTriangle(), loadMesh(), queryPointLocation(), tagMesh(), and writeMesh().
std::vector<moab::EntityHandle> MoabMesh::_tris private
Definition at line 46 of file moabmesh.h.
Referenced by _identifyBoundaryElements(), _identifyEdges(), loadMesh(), and tagMesh().
moab::Range MoabMesh::_verts private
Definition at line 47 of file moabmesh.h.
Referenced by loadMesh(), tagMesh(), and writeMesh().
double* MoabMesh::_x private
Definition at line 56 of file moabmesh.h.
Referenced by getCurrentElementFromID(), getElementVolume(), and loadMesh().
double* MoabMesh::_y private
Definition at line 57 of file moabmesh.h.
Referenced by getCurrentElementFromID(), getElementVolume(), and loadMesh().
double* MoabMesh::_z private
Definition at line 58 of file moabmesh.h.
Referenced by getCurrentElementFromID(), and loadMesh().
std::vector<long> MoabMesh::boundaryElements
Definition at line 40 of file moabmesh.h.
Referenced by SolverLocalMOC::_applyBoundaryConditions(), SolverRegMOC::_applyBoundaryConditions(), and _identifyBoundaryElements().
The documentation for this class was generated from the following files:
include/moabmesh.h
src/moabmesh.cpp