Radiation Transport Code: SolverLocalMOC Class Reference
SolverLocalMOC Class Reference
LocalMOC Solver.
#include <solverlocalmoc.h>
Public Member Functions
SolverLocalMOC (TransportProblem &tp)
~SolverLocalMOC ()
void solve ()
Implementation of the LocalMOC solver.
double * getResidual ()
double getScalarFlux (long space_i, int group_g)
Public Member Functions inherited from SolverBase
virtual ~SolverBase ()
double calculateL2SolutionNorm (double *solutionComp)
double calculateLInfSolutionNorm (double *solutionComp)
double calculateRInfSolutionNorm (double *solutionComp)
double calculateL2SolutionError ()
double calculateRInfSolutionError ()
const double * getSolutionValue (long space_i, int quad_n, int group_g)
const double * getSolutionValue (long i)
long getNumDOFs ()
TransportProblem & getTransportProblem ()
double getNeutronProduction (long space_i)
double getTotalNeutronProduction ()
void setRInfTol (double tol)
void setMaxIters (int maxIters)
void setSolution (double *solution)
double * copySolution (double *solutionCopy)
void normalizeSolution (double totalProductionRate)
void zeroSolution ()
void extrapolateSolution (double expExtrapFactor)
void extrapolateSolution (double expExtrapFactor, double *baseSolution)
void writeSolution (Output *outputFile)
void writeScalarFlux (Output *outputFile)
void printIterStatus (std::string name, int iter, double err, double tol)
Private Member Functions
unsigned long _dofIndex (long i, int n, int g, int edgeLoc=0)
void _mapDOFs ()
Map degrees-of-freedom.
void _calculateSphericalQuadrature ()
Get spherical representation of ordinates.
int _getReflectedDirection (int i, double nx, double ny, double &OmegaDotn)
void _sweep (int n)
Mesh sweep.
void _getTriangleOrientation (UltraLightElement &element2, int n, double &mu01, double &mu12, double &mu20, double &pathDist, int &evDir, int &veDir, long &edgeNeighbor, long &vertexNeighbor1, long &vertexNeighbor2, int &xedge, int &v0, int &v1, int &v2, double &surfacePosition)
double _getAngleFromVector (double dx, double dy)
Calculate the azimuthal angle of a vector with components dx and dy.
void _calculateSource (double *fissionFlux)
void _getExternalSource ()
void _addScatterSource ()
void _calculateMatrixAction (double *x, double *y)
void _applyBoundaryConditions ()
Private Attributes
std::vector< double > _mu
std::vector< double > _theta
std::vector< int > _negDir
MoabMesh * mesh
double * _cellFlux
double * _surfacePosition
unsigned int _numPhaseSpaceDOF
Additional Inherited Members
Public Attributes inherited from SolverBase
SourceConfiguration sourceConfig
double sourceScaling
This scales the external source, but is used as a fission source in the power method.
double criticalEigenvalue
"Critical" eigenvalue for transient calculations based on ICs from an eigenvalue calculation
Protected Member Functions inherited from SolverBase
SolverBase (TransportProblem &tp)
Constructor.
void _calculateResidual ()
void _saveOldSolution ()
Protected Attributes inherited from SolverBase
TransportProblem & _prob
Reference to the base transport problem.
long _numDOF
Number of DOF.
long _numSpaceDOF
Number of spatial DOF.
std::vector< DOFObj > DOFlist
List of DOF (currently unused)
std::map< DOFObj, double * > DOFmap
DOF map.
double * _solution
Solution vector.
double * _residual
Residual vector.
double * _source
Source vector.
double * _h
Mesh spacing.
double * _solutionPrev
double _convRInfTol
int _maxIters
std::map< DOFObj, double > _bdryFlux
Detailed Description
LocalMOC Solver.
Still under active development
Definition at line 12 of file solverlocalmoc.h.
Constructor & Destructor Documentation
SolverLocalMOC::SolverLocalMOC (TransportProblem & tp)
Definition at line 7 of file solverlocalmoc.cpp.
References _calculateSphericalQuadrature(), _cellFlux, _mapDOFs(), SolverBase::_numDOF, _numPhaseSpaceDOF, SolverBase::_numSpaceDOF, SolverBase::_prob, SolverBase::_residual, SolverBase::_solution, SolverBase::_solutionPrev, SolverBase::_source, _surfacePosition, LOG_DBG, LOG_ERR, TransportProblem::mesh, mesh, TransportProblem::numCells, TransportProblem::numEdges, TransportProblem::numGroups, and TransportProblem::quadOrder.
SolverLocalMOC::~SolverLocalMOC ()
Definition at line 45 of file solverlocalmoc.cpp.
References _cellFlux, SolverBase::_residual, SolverBase::_solution, SolverBase::_solutionPrev, and SolverBase::_source.
Member Function Documentation
void SolverLocalMOC::_addScatterSource () private
Definition at line 708 of file solverlocalmoc.cpp.
References _dofIndex(), SolverBase::_prob, SolverBase::_source, MoabMesh::getElementMat(), getScalarFlux(), Material::getSigma_s(), mesh, TransportProblem::numCells, TransportProblem::numGroups, and TransportProblem::quadOrder.
Referenced by _calculateSource().
void SolverLocalMOC::_applyBoundaryConditions () private
Definition at line 483 of file solverlocalmoc.cpp.
References SolverBase::_bdryFlux, _dofIndex(), _getReflectedDirection(), _getTriangleOrientation(), _mu, SolverBase::_prob, SolverBase::_solution, _theta, MoabMesh::boundaryElements, MoabMesh::getCurrentElementFromID(), TransportProblem::globalBC, mesh, norm(), TransportProblem::numGroups, TransportProblem::nxnyq, reflecting, source, vacuum, UltraLightElement::x, and UltraLightElement::y.
Referenced by solve().
void SolverLocalMOC::_calculateMatrixAction (double * x, double * y) private virtual
Implements SolverBase.
Definition at line 728 of file solverlocalmoc.cpp.
void SolverLocalMOC::_calculateSource (double * fissionFlux) private
Definition at line 678 of file solverlocalmoc.cpp.
References _addScatterSource(), and _getExternalSource().
Referenced by solve().
void SolverLocalMOC::_calculateSphericalQuadrature () private
Get spherical representation of ordinates.
Calculate (theta, mu) coordinates from the input (omega_x, omega_y, omega_z). Also get the mapping between each ordinate, u, and its negative, -v. Currently only two-dimensional problems are assumed, so the polar cosine, mu, is assumed symmetric about the xy-plane.
Definition at line 79 of file solverlocalmoc.cpp.
References _getAngleFromVector(), _mu, _negDir, SolverBase::_prob, _theta, LOG_ERR, TransportProblem::omega_x, TransportProblem::omega_y, TransportProblem::omega_z, pi, and TransportProblem::quadOrder.
Referenced by SolverLocalMOC().
unsigned long SolverLocalMOC::_dofIndex (long i, int n, int g, int edgeLoc = 0) inline private
Definition at line 22 of file solverlocalmoc.h.
References SolverBase::_prob, TransportProblem::numGroups, and TransportProblem::quadOrder.
Referenced by _addScatterSource(), _applyBoundaryConditions(), _getExternalSource(), _mapDOFs(), _sweep(), and getScalarFlux().
double SolverLocalMOC::_getAngleFromVector (double dx, double dy) private
Calculate the azimuthal angle of a vector with components dx and dy.
Definition at line 662 of file solverlocalmoc.cpp.
References pi.
Referenced by _calculateSphericalQuadrature(), _getReflectedDirection(), and _getTriangleOrientation().
void SolverLocalMOC::_getExternalSource () private
Definition at line 688 of file solverlocalmoc.cpp.
References _dofIndex(), SolverBase::_numDOF, SolverBase::_prob, SolverBase::_source, TransportProblem::getExtSource(), SourceConfiguration::hasExternalSource, TransportProblem::numCells, TransportProblem::numGroups, TransportProblem::quadOrder, SolverBase::sourceConfig, and SolverBase::sourceScaling.
Referenced by _calculateSource().
int SolverLocalMOC::_getReflectedDirection (int i, double nx, double ny, double & OmegaDotn) private
Definition at line 111 of file solverlocalmoc.cpp.
References _getAngleFromVector(), _mu, SolverBase::_prob, _theta, LOG_DBG, LOG_ERR, and TransportProblem::quadOrder.
Referenced by _applyBoundaryConditions().
void SolverLocalMOC::_getTriangleOrientation (UltraLightElement & element2, int n, double & mu01, double & mu12, double & mu20, double & pathDist, int & evDir, int & veDir, long & edgeNeighbor, long & vertexNeighbor1, long & vertexNeighbor2, int & xedge, int & v0, int & v1, int & v2, double & surfacePosition) private
Definition at line 301 of file solverlocalmoc.cpp.
References _getAngleFromVector(), _negDir, _theta, UltraLightElement::neighborID, pi, UltraLightElement::x, UltraLightElement::y, and UltraLightElement::z.
Referenced by _applyBoundaryConditions(), and _sweep().
void SolverLocalMOC::_mapDOFs () private virtual
Map degrees-of-freedom.
Implements SolverBase.
Definition at line 57 of file solverlocalmoc.cpp.
References _dofIndex(), SolverBase::_numDOF, SolverBase::_prob, SolverBase::_solution, SolverBase::DOFlist, SolverBase::DOFmap, TransportProblem::numCells, TransportProblem::numGroups, and TransportProblem::quadOrder.
Referenced by SolverLocalMOC().
void SolverLocalMOC::_sweep (int n) private
Mesh sweep.
A MoabMesh must be used.
Definition at line 187 of file solverlocalmoc.cpp.
References SolverBase::_bdryFlux, _cellFlux, _dofIndex(), _getTriangleOrientation(), _mu, SolverBase::_prob, SolverBase::_solution, SolverBase::_source, _surfacePosition, MoabMesh::getCurrentElementFromID(), MoabMesh::getEdgeID(), MoabMesh::getElementMat(), Sweeper::getNextElementID(), Material::getSigma_t(), mesh, and TransportProblem::numGroups.
Referenced by solve().
double* SolverLocalMOC::getResidual ()
double SolverLocalMOC::getScalarFlux (long space_i, int group_g) virtual
Implements SolverBase.
Definition at line 733 of file solverlocalmoc.cpp.
References _cellFlux, _dofIndex(), SolverBase::_prob, TransportProblem::quadOrder, and TransportProblem::weights.
Referenced by _addScatterSource().
void SolverLocalMOC::solve () virtual
Implementation of the LocalMOC solver.
Implements SolverBase.
Definition at line 140 of file solverlocalmoc.cpp.
References _applyBoundaryConditions(), _calculateSource(), SolverBase::_convRInfTol, SolverBase::_maxIters, SolverBase::_prob, SolverBase::_saveOldSolution(), SolverBase::_solution, SolverBase::_solutionPrev, _sweep(), SolverBase::calculateRInfSolutionNorm(), SolverBase::copySolution(), SourceConfiguration::hasFissionSource, SolverBase::printIterStatus(), TransportProblem::quadOrder, and SolverBase::sourceConfig.
Member Data Documentation
double* SolverLocalMOC::_cellFlux private
Definition at line 34 of file solverlocalmoc.h.
Referenced by _sweep(), getScalarFlux(), SolverLocalMOC(), and ~SolverLocalMOC().
std::vector<double> SolverLocalMOC::_mu private
Definition at line 28 of file solverlocalmoc.h.
Referenced by _applyBoundaryConditions(), _calculateSphericalQuadrature(), _getReflectedDirection(), and _sweep().
std::vector<int> SolverLocalMOC::_negDir private
Definition at line 30 of file solverlocalmoc.h.
Referenced by _calculateSphericalQuadrature(), and _getTriangleOrientation().
unsigned int SolverLocalMOC::_numPhaseSpaceDOF private
Definition at line 52 of file solverlocalmoc.h.
Referenced by SolverLocalMOC().
double* SolverLocalMOC::_surfacePosition private
Definition at line 35 of file solverlocalmoc.h.
Referenced by _sweep(), and SolverLocalMOC().
std::vector<double> SolverLocalMOC::_theta private
Definition at line 29 of file solverlocalmoc.h.
Referenced by _applyBoundaryConditions(), _calculateSphericalQuadrature(), _getReflectedDirection(), and _getTriangleOrientation().
MoabMesh* SolverLocalMOC::mesh private
Definition at line 32 of file solverlocalmoc.h.
Referenced by _addScatterSource(), _applyBoundaryConditions(), _sweep(), and SolverLocalMOC().
The documentation for this class was generated from the following files:
include/solverlocalmoc.h
src/solverlocalmoc.cpp