Radiation Transport Code: InputParser Class Reference
InputParser Class Reference
Input parser object.
#include <inputparser.h>
Public Member Functions
InputParser ()
~InputParser ()
bool parseInputFile (std::string fileName)
int countSets (std::vector< std::string > path)
std::vector< double > getVector (std::vector< std::string > path, std::string varName, int setNumber=1)
std::string getString (std::vector< std::string > path, std::string varName, int setNumber=1)
void setVector (std::vector< std::string > path, std::string varName, std::vector< double > &varData, int setNumber=1)
void echoInput ()
Private Member Functions
bool _readInputFile (std::string fileName)
bool _parseInput ()
bool _check ()
bool _fillIn ()
Private Attributes
std::string fileContents
DataSetGrammar
< std::string::const_iterator > inputGrammar
DataSetStruct inputData
GetFromSet setRead
Detailed Description
Input parser object.
This class reads in all of the data sets from the input file and stores the result as a DataSetStruct.
Definition at line 88 of file inputparser.h.
Constructor & Destructor Documentation
InputParser::InputParser ()
Definition at line 4 of file inputparser.cpp.
InputParser::~InputParser ()
Definition at line 8 of file inputparser.cpp.
Member Function Documentation
bool InputParser::_check () private
Definition at line 41 of file inputparser.cpp.
References countSets(), getString(), and LOG_ERR.
Referenced by parseInputFile().
bool InputParser::_fillIn () private
Definition at line 119 of file inputparser.cpp.
References getVector(), and setVector().
bool InputParser::_parseInput () private
Definition at line 30 of file inputparser.cpp.
References fileContents, inputData, and inputGrammar.
Referenced by parseInputFile().
bool InputParser::_readInputFile (std::string fileName) private
Definition at line 136 of file inputparser.cpp.
References fileContents.
Referenced by parseInputFile().
int InputParser::countSets (std::vector< std::string > path) inline
Definition at line 96 of file inputparser.h.
Referenced by _check(), MaterialFactory::createMaterialsFromInput(), main(), and TransportProblem::TransportProblem().
void InputParser::echoInput ()
Definition at line 22 of file inputparser.cpp.
References inputData.
Referenced by main().
std::string InputParser::getString (std::vector< std::string > path, std::string varName, int setNumber = 1) inline
Definition at line 104 of file inputparser.h.
Referenced by _check(), MeshFactory::createMeshFromInput(), main(), MaterialFactory::readNextMaterial(), SolutionManager::SolutionManager(), Transient::Transient(), and TransportProblem::TransportProblem().
std::vector<double> InputParser::getVector (std::vector< std::string > path, std::string varName, int setNumber = 1) inline
Definition at line 99 of file inputparser.h.
Referenced by _fillIn(), MeshFactory::createMeshFromInput(), MaterialFactory::readNextMaterial(), SolutionManager::SolutionManager(), Transient::Transient(), Transient_NDAdaptive::Transient_NDAdaptive(), and TransportProblem::TransportProblem().
bool InputParser::parseInputFile (std::string fileName)
Definition at line 14 of file inputparser.cpp.
References _check(), _parseInput(), and _readInputFile().
Referenced by main().
void InputParser::setVector (std::vector< std::string > path, std::string varName, std::vector< double > & varData, int setNumber = 1) inline
Definition at line 109 of file inputparser.h.
Referenced by _fillIn().
Member Data Documentation
std::string InputParser::fileContents private
Definition at line 123 of file inputparser.h.
Referenced by _parseInput(), and _readInputFile().
DataSetStruct InputParser::inputData private
Definition at line 125 of file inputparser.h.
Referenced by _parseInput(), and echoInput().
DataSetGrammar<std::string::const_iterator> InputParser::inputGrammar private
Definition at line 124 of file inputparser.h.
Referenced by _parseInput().
GetFromSet InputParser::setRead private
Definition at line 126 of file inputparser.h.
The documentation for this class was generated from the following files:
include/inputparser.h
src/inputparser.cpp