Radiation Transport Code: DataSetGrammar< Iterator > Struct Template Reference
DataSetGrammar< Iterator > Struct Template Reference
Grammar for reading a data set consisting of zero or more data nodes.
#include <inputparser.h>
Public Member Functions
DataSetGrammar ()
Public Attributes
qi::rule< Iterator,
DataSetStruct(), qi::locals
< std::string >
, ascii::space_type > DataSet_r
qi::rule< Iterator, DataNode(),
ascii::space_type > DataNode_r
qi::rule< Iterator,
std::string(),
ascii::space_type > startSet
qi::rule< Iterator, void(std::string),
ascii::space_type > endSet
NamedArrayGrammar< Iterator > nag
NamedStringGrammar< Iterator > nsg
Detailed Description
template<typename Iterator>
struct DataSetGrammar< Iterator >
Grammar for reading a data set consisting of zero or more data nodes.
Each data node is either a named array, named string, or another data set.
Definition at line 55 of file inputparser.h.
Constructor & Destructor Documentation
template<typename Iterator> DataSetGrammar< Iterator >::DataSetGrammar () inline
Definition at line 57 of file inputparser.h.
Member Data Documentation
template<typename Iterator> qi::rule<Iterator, DataNode(), ascii::space_type> DataSetGrammar< Iterator >::DataNode_r
Definition at line 75 of file inputparser.h.
Referenced by DataSetGrammar< std::string::const_iterator >::DataSetGrammar().
template<typename Iterator> qi::rule<Iterator, DataSetStruct(), qi::locals<std::string>, ascii::space_type> DataSetGrammar< Iterator >::DataSet_r
Definition at line 74 of file inputparser.h.
Referenced by DataSetGrammar< std::string::const_iterator >::DataSetGrammar().
template<typename Iterator> qi::rule<Iterator, void(std::string), ascii::space_type> DataSetGrammar< Iterator >::endSet
Definition at line 77 of file inputparser.h.
Referenced by DataSetGrammar< std::string::const_iterator >::DataSetGrammar().
template<typename Iterator> NamedArrayGrammar<Iterator> DataSetGrammar< Iterator >::nag
Definition at line 78 of file inputparser.h.
Referenced by DataSetGrammar< std::string::const_iterator >::DataSetGrammar().
template<typename Iterator> NamedStringGrammar<Iterator> DataSetGrammar< Iterator >::nsg
Definition at line 79 of file inputparser.h.
Referenced by DataSetGrammar< std::string::const_iterator >::DataSetGrammar().
template<typename Iterator> qi::rule<Iterator, std::string(), ascii::space_type> DataSetGrammar< Iterator >::startSet
Definition at line 76 of file inputparser.h.
Referenced by DataSetGrammar< std::string::const_iterator >::DataSetGrammar().
The documentation for this struct was generated from the following file:
include/inputparser.h